apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuberisc-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: kuberisc-agent
  template:
    metadata:
      labels:
        app: kuberisc-agent
    spec:
      serviceAccountName: kuberisc-agent
      containers:
        - name: agent
          image: ghcr.io/wangqihao-charlie/kuberisc-agent:latest
          imagePullPolicy: Always
          args:
            - --metrics-addr=:8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AGENT_CONCURRENCY
              value: "4"
            # Optional: use labelSelector for server-side filtering (recommended for CRDs)
            - name: NA_NODE_LABEL
              value: "risc.dev/node"
            # gRPC runtime driver endpoint (using UDS on host)
            - name: DRIVER_ADDR
              value: "unix:///var/run/driverd/runtime-driver.grpc"
            - name: DRIVER_INSECURE
              value: "true"
            # Configure CRD GVRs if different from defaults
            - name: NA_GROUP
              value: "risc.dev"
            - name: NA_VERSION
              value: "v1alpha1"
            - name: NA_RESOURCE
              value: "nodeactions"
            - name: IS_GROUP
              value: "risc.dev"
            - name: IS_VERSION
              value: "v1alpha1"
            - name: IS_RESOURCE
              value: "instructionsets"
          ports:
            - name: metrics
              containerPort: 8080
          volumeMounts:
            - name: driver-sock
              mountPath: /var/run/driverd
      volumes:
        # Mount the driver socket directory from the host
        - name: driver-sock
          hostPath:
            path: /var/run/driverd
            type: Directory
